### ISSUE TITLE
Bugs here and there

### ISSUE THREAD

**Issue by truekonrads** [fastlorenzo/redelk-server#2]
Hello,

Some bugs I found when I was trying to set it up on AWS Ubuntu 20 AMI.
### APT packages missing
The playbook assumes certain packages already exist when they don't always:

- python3-pip
- docker

### Missing becomes

- It also fails if the user which you run redelk as (e.g. I run it as ubuntu on AWS) isn't root (the task docker is missing one become:true)
- There is a missing become for handler "init-letsencrypt.sh"
### Missing python modules
It is missing a python module passlib and it fails without it. I _think_ it does intall it but it doesn't install it system-wide and so when you become on other tasks it bombs out.

### Missing ansible requirments
There is a requirement on  community.crypto module.

Also it consumes a fair amount of disk space. There should be a check for it.

**Comment by fastlorenzo** [comment]
Thanks, I've merged your PR #5 
From there, it looks like the only remaining issue is the dependency on  `community.crypto`, I'll get it in there as well

**Comment by fastlorenzo** [comment]
Closed in master
