### ISSUE TITLE
Local RedElk cert directory does not always exist

### ISSUE THREAD

**Issue by truekonrads** [fastlorenzo/redelk-server#4]
TASK [redelk-server : Fetch redelk certificates] ***********************************************************************************************************************************************************************************
fatal: [redelk]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -C -o ControlMaster=auto -o ControlPersist=60s --rsync-path=sudo rsync --out-format=<<CHANGED>>%i %n%L ubuntu@3.0.51.223:/opt/redelk/mounts/certs/ /home/truekonrads/certificates/redelk/", "msg": "Warning: Permanently added '3.0.51.223' (ECDSA) to the list of known hosts.\r\nrsync: mkdir \"/home/truekonrads/certificates/redelk\" failed: No such file or directory (2)\nrsync error: error in file IO (code 11) at main.c(682) [Receiver=3.1.3]\n", "rc": 11}

**Comment by fastlorenzo** [comment]
Fixed in [ce702f6](https://github.com/fastlorenzo/redelk-server/commit/ce702f665fb5fa23d99e580220418d8b23d36486)
